export const environment = {
  production: false,
  t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-IPS:T-ETK:T-RAS:T-PPB:T-PET:T-MTS:T-TIL:T-DGF:T-NAT:F-HPB:T-TOW:F',
  VERSION: require('../../package.json').version,
  remoteConfig: true, 
  // remoteConfigUrl: './design-studio-config.json',
  // remoteConfigUrl: '/environments/real_data/cds-config-native-prod.json',
  // remoteConfigUrl: '/environments/real_data/cds-config-native-collaudo.json',
  remoteConfigUrl: '/environments/real_data/cds-config-firebase.json',
  globalRemoteJSSrc: 'https://support-pre.tiledesk.com/script/segment_script.js',
  apiUrl: 'https://tiledesk-server-pre.herokuapp.com/',
  widgetBaseUrl: 'https://widget-pre.tiledesk.com/v5/',
  dashboardBaseUrl: 'https://support-pre.tiledesk.com/dashboard/',
  whatsappTemplatesBaseUrl: "https://tiledesk-whatsapp-connector.giovannitroisi3.repl.co",
  wsUrl: 'wss://tiledesk-server-pre.herokuapp.com/',
  uploadEngine: 'firebase',
  baseImageUrl: 'https://firebasestorage.googleapis.com/v0/b/',
  logLevel: 'debug',
  storage_prefix: "cds_sv6",
  brandSrc: 'CHANGEIT',
  firebaseConfig: {
    apiKey: "AIzaSyCoWXHNvP1-qOllCpTshhC6VjPXeRTK0T4",
      authDomain: "chat21-pre-01.firebaseapp.com",
      databaseURL: "https://chat21-pre-01.firebaseio.com",
      projectId: "chat21-pre-01",
      storageBucket: "chat21-pre-01.appspot.com",
      messagingSenderId: "269505353043",
      appId: "1:269505353043:web:b82af070572669e3707da6",
      vapidKey: "BOsgS2ADwspKdWAmiFDZXEYqY1HSYADVfJT3j67wsySh3NxaViJqoabPJH8WM02wb5r8cQIm5TgM0UK047Z1D1c"
  }
};